# Generated by Django 5.2 on 2025-04-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_staffrestaurant_expenditure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffrestaurant',
            name='expenditure',
        ),
        migrations.AddField(
            model_name='sale',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
