# Generated by Django 5.2 on 2025-04-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_restaurant_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
