# Generated by Django 5.2 on 2025-04-11 08:04

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_rating_rating_alter_rating_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': [django.db.models.functions.text.Lower('name'), 'date_opened']},
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('restaurant', models.ManyToManyField(to='app.restaurant')),
            ],
        ),
    ]
